### ISSUE TITLE
Can't authorize myself

### ISSUE THREAD

**Issue by martiabernathey** [pthuencher/jukebot-telegram#6]
I apologize if I'm not doing this right, it's literally my first "issue" posting here on GIthub. I've ssh'd into my machine and set up the bot. When I try interacting with the bot I got this on telegram: 

```
Martha Abernathy, [1/14/2022 10:03 PM]
/start

TpartyYoutubebot, [1/14/2022 10:03 PM]
Error: not authorized. /request_access

Martha Abernathy, [1/14/2022 10:03 PM]
/request_access

TpartyYoutubebot, [1/14/2022 10:03 PM]
Access request send.

TpartyYoutubebot, [1/14/2022 10:03 PM]
Access Request by martiabernathey (Martha Abernathy None). Use /grant *my UID* to grant access.

Martha Abernathy, [1/14/2022 10:04 PM]
/grant *my UID*

TpartyYoutubebot, [1/14/2022 10:04 PM]
Error: not authorized.
```

and this is what I get on the backend:

`2022-01-13 22:27:01,684 - telegram.bot - DEBUG - {'text': 'Error: Chat not found', 'photo': [], 'channel_chat_created': False, 'caption_entities': [], 'group_chat_created': False, 'supergroup_chat_created': False, 'date': 1642112821, 'new_chat_members': [], 'chat': {'username': 'martiabernathey', 'type': 'private', 'id': *my UID*, 'first_name': 'Martha Abernathy'}, 'message_id': 32, 'new_chat_photo': [], 'entities': [{'type': 'bold', 'offset': 0, 'length': 6}], 'delete_chat_photo': False, 'from': {'username': 'martiabernathytpartybot', 'id': 5006819413, 'is_bot': True, 'first_name': 'TpartyYoutubebot'}}`

**Comment by pthuencher** [comment]
You need to set your user id as `ADMIN_UID` in config.py

**Comment by martiabernathey** [comment]
This is from my config.py:

```
# READ FIRST: 
# Set BOT_TOKEN and rename this file to "config.py"

BOT_TOKEN: str = "*bot token from the botfather* " 
ADMIN_UID: int = "*UID from the Userinfobot*"
WORK_DIR: str = "tmp-workdir"

WHITELIST_FILE: str = "whitelist.txt"
YOUTUBE_COOKIE_FILE: str = 'cookies.txt'
```

The user ID is a number, correct? 

or are you saying it needs to be:
```

BOT_TOKEN: str = "*bot token from the botfather* " 
ADMIN_UID: int = "ADMIN_UID"
WORK_DIR: str = "tmp-workdir"

WHITELIST_FILE: str = "whitelist.txt"
YOUTUBE_COOKIE_FILE: str = 'cookies.txt'
```

**Comment by Diniodoc** [comment]
I run in the same issue, you have to declare the ADMIN_UID as numeric not as string and it will work.

**Comment by martiabernathey** [comment]
> I run in the same issue, you have to declare the ADMIN_UID as numeric not as string and it will work.

I asked the userinfobot for my id then popped it in like so:

ADMIN_UID:  int = "123456789"

Right?

**Comment by Diniodoc** [comment]
Yea but without the quotation marks, just: 

ADMIN_UID: int = 123456789
